# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_auto_20170207_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Game', to=settings.AUTH_USER_MODEL),
        ),
    ]
