# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0003_auto_20170212_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='status',
            field=models.CharField(default='rnbqkbnr/pppppppp/......../......../......../......../PPPPPPPP/RNBQKBNR//', max_length=100),
        ),
    ]
